### ISSUE TITLE
Line over 120 chars long

### ISSUE THREAD

**Issue by robknows** [kaashif/rice_info#1]
You seem to have a line over 120 characters long [here](https://github.com/kaashif/rice_info/blob/master/rice_info/__init__.py#L27). This code is literally unusable, I had to buy a new monitor to be able to fit the whole line in my terminal while still having the terminals tessellate horizontally on my screen. Can you fix this asap?

**Comment by kaashif** [comment]
`pylint` tells my that the code in this repo is rated -6/10 for quality. You just don't get code like this anywhere else. Closed for lack of appreciation of my genius.
